model:
  path: "/lustre/fsn1/projects/rech/knb/umq83db/Models/Qwen3-0.6B"
training:
  max_seq_length: 128
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 4
  warmup_steps: 100
  num_train_epochs: 6
  learning_rate: 2e-5
  logging_steps: 200
  eval_steps: 500
  save_steps: 1000
data:
  train_json: "/lustre/fsn1/projects/rech/knb/umq83db/Datasets/train.json"
  eval_paths:
    - "/lustre/fsn1/projects/rech/knb/umq83db/Datasets/eval_data_easy"
    - "/lustre/fsn1/projects/rech/knb/umq83db/Datasets/eval_data_skip_one_stop"
    - "/lustre/fsn1/projects/rech/knb/umq83db/Datasets/eval_data_skip_two_stops"
    - "/lustre/fsn1/projects/rech/knb/umq83db/Datasets/eval_data_skip_three_stops"
  eval_bus_path:
    - "/lustre/fsn1/projects/rech/knb/umq83db/Datasets/eval_data_pair_line"
wandb:
  project: "full_fine_tuning"
  mode: "offline"
